In [4]:
import numpy as np
X = np.arange(20).reshape(4, 5)

print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [9]:
Z = X[:, 2:3]
Z

array([[ 2],
       [ 7],
       [12],
       [17]])

In [10]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
Z = np.copy(X[1:4, 2:5])
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [14]:
W = X[1:4, 2:5].copy()
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [15]:
Z[2, 2] = 555
Z

array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 555]])

In [16]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
indices = np.array([1, 3])
indices

array([1, 3])

In [25]:
Y = X[indices, :]
Y

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [26]:
V = X[:, indices]
V

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [29]:
A = np.random.randint(1, 20, size = (50, 5))
print("Shape of A is: ", A.shape)


Shape of A is:  (50, 5)


In [30]:
row_indices = np.random.randint(0,50, size=10)
print("Random 10 indices are: ", row_indices)

Random 10 indices are:  [17  1 23 41  4 48 39 12 41 22]


In [31]:
X = np.arange(25).reshape(5, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
print(np.diag(X))

[ 0  6 12 18 24]


In [33]:
print(np.diag(X, k = 1))

[ 1  7 13 19]


In [34]:
print(np.diag(X, k = -1))

[ 5 11 17 23]
